#!/usr/bin/env python3
#
# Launched by udev when the Mustang amp or the MIDI controller is
# unplugged.  Asks a running bridge to shut down cleanly (SIGINT).

import os
import signal
from glob import glob
from syslog import syslog

pid = os.getpid()

rundir = "/var/run/mustang/"

# Check for pid file
os.chdir(rundir)
filelist = glob('mustang_*')

if len(filelist) == 1:
    lockfile = filelist[0]
    oldpid = lockfile.split('_')[1]

    # See if the process still exists
    if os.path.exists("/proc/%s" % oldpid):
        try:
            os.kill(int(oldpid), signal.SIGINT)
        except OSError as e:
            syslog("%d: Signal failed: %s" % (pid, e))
else:
    syslog("%d: /var/run/mustang is not properly setup" % pid)
